services:
- docker
script:
- docker run -it -v ${PWD}:/workdir whatever4711/latex latexmk -pdf cookbook.tex
- ls -la ${PWD}
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: cookbook.pdf
  skip_cleanup: true
  on:
    repo: whatever4711/cookbook
    tags: true
