env:
  global:
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64

sudo: required
services:
  - docker

# Building pdf by using a docker container
script:
  - docker pull unibaktr/latex:jessie
  - docker run -it -v ${PWD}:/src unibaktr/latex:jessie latexmk -c -pdf cookbook.tex
  - ls -la ${PWD}
