env:
  global:
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
sudo: required
services:
- docker
script:
- docker pull whatever4711/latex
- docker run -it -v ${PWD}:/workdir whatever4711/latex latexmk -pdf cookbook.tex
- ls -la ${PWD}
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: cookbook.pdf
  skip_cleanup: true
  on:
    repo: whatever4711/cookbook
    tags: true
